// <auto-generated />
namespace archivesystemWebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addUserRolesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addUserRolesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202102101139587_addUserRolesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
